services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-le_xot}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-lists}
    volumes:
      - pgdata:/var/lib/postgresql/data

  admin:
    image: adminer
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - default
      - caddy
    labels:
      caddy: adminer.le-xot.dev
      caddy.reverse_proxy: '{{upstreams 8080}}'

  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: lexot/games-movies-database:latest
    restart: unless-stopped
    depends_on:
      - postgres
    env_file: .env
    environment:
      DATASOURCE_URL: postgresql://${POSTGRES_USER:-le_xot}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-lists}?schema=public
    networks:
      - default
      - caddy
    labels:
      caddy: le-xot.dev
      caddy.reverse_proxy: '{{upstreams 3000}}'

volumes:
  pgdata:

networks:
  caddy:
    external: true
