export const ROUTER_PATHS = {
  home: "/",
  db: "/db",
  pc: "/pc",
  admin: "/db/admin",
  profile: "/db/profile",
  dbQueue: "/db/queue",
  dbGames: "/db/games",
  dbAnime: "/db/anime",
  dbMovie: "/db/movie",
  dbCartoon: "/db/cartoon",
  dbSeries: "/db/series",
  dbSuggestion: "/db/suggestion",
  dbAuction: "/db/auction",
}
