export { default as Pagination } from '@/components/ui/pagination/Pagination.vue'
export { default as PaginationContent } from '@/components/ui/pagination/PaginationContent.vue'
export { default as PaginationEllipsis } from '@/components/ui/pagination/PaginationEllipsis.vue'
export { default as PaginationFirst } from '@/components/ui/pagination/PaginationFirst.vue'
export { default as PaginationItem } from '@/components/ui/pagination/PaginationItem.vue'
export { default as PaginationLast } from '@/components/ui/pagination/PaginationLast.vue'
export { default as PaginationNext } from '@/components/ui/pagination/PaginationNext.vue'
export { default as PaginationPrevious } from '@/components/ui/pagination/PaginationPrevious.vue'
