export const UserRole = 'UserRole'
export const AccountPlatform = 'AccountPlatform'
export const RecordStatus = 'RecordStatus'
export const RecordType = 'RecordType'
export const RecordGenre = 'RecordGenre'
export const RecordGrade = 'RecordGrade'
export const LimitType = 'LimitType'
export const WordleGameStatus = 'WordleGameStatus'
