export const StatusesEnum = 'StatusesEnum'
export const GenresEnum = 'GenresEnum'
export const GradeEnum = 'GradeEnum'
export const TypesEnum = 'TypesEnum'
export const RolesEnum = 'RolesEnum'
export const SuggestionsTypeEnum = 'SuggestionsTypeEnum'
export const LimitTypeEnum = 'LimitTypeEnum'
